In [ ]:
import pandas as pd
import numpy as np
import textwrap #new
import nltk
from nltk.corpus import stopwords
from nltk import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
df = pd.read_csv("/content/drive/Othercomputers/Mon ordinateur portable/Data Science/Text_Summary/df_total.csv")

In [ ]:
df.head()

url  ...           Type
0  https://www.larepublica.co/redirect/post/3201905  ...           Otra
1  https://www.larepublica.co/redirect/post/3210288  ...   Regulaciones
2  https://www.larepublica.co/redirect/post/3240676  ...       Alianzas
3  https://www.larepublica.co/redirect/post/3342889  ...  Macroeconomia
4  https://www.larepublica.co/redirect/post/3427208  ...           Otra

[5 rows x 3 columns]

In [ ]:
df.tail()

url  ...           Type
1212  https://www.bbva.com/es/como-lograr-que-los-in...  ...     Innovacion
1213  https://www.bbva.com/es/podcast-como-nos-afect...  ...  Macroeconomia
1214   https://www.larepublica.co/redirect/post/3253735  ...       Alianzas
1215  https://www.bbva.com/es/bbva-y-barcelona-healt...  ...     Innovacion
1216   https://www.larepublica.co/redirect/post/3263980  ...       Alianzas

[5 rows x 3 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1217 entries, 0 to 1216
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   url     1217 non-null   object
 1   news    1217 non-null   object
 2   Type    1217 non-null   object
dtypes: object(3)
memory usage: 28.6+ KB


In [ ]:
#we will only use the 'news' column for our work
print(df['news'][18])

BBVA acompañó la realización de la primera edición de Impulsando Argentina un evento organizado por Unión Argentina de Jóvenes Empresarios UNAJE que se dio cita en la Torre BBVA en Buenos Aires.El encuentro se inició con la participación de Martín Zarich presidente de BBVA en Argentina en el panel titulado Consensos Económicos que invitó a reflexionar desde distintos ángulos los acuerdos políticos que se requieren para el crecimiento de Argentina tanto desde el sector público pero también del sector privado.Martín Zarich explicó Tanto el sector público como las empresas tenemos que tener el compromiso y hacer un diagnóstico sobre las necesidades de la sociedad y así generar los consensos necesarios. Es central hacer sentir la voz de nuestro sector en relación a las necesidades del país para poder crecer.Seguidamente Cecilia Todesca Bocco secretaria de Relaciones Económicas Internacionales de la Cancillería argentina indicó que hoy hay sectores que Argentina tiene para desarrollar y hac

In [ ]:
#The idea is: for each news divide it into tokens (here token = sentence)
#Then transform each token in vector with tfidf
#Then score each word of the token (ranking)
#Then we do the summary using the best importance words

for i in range(0,100):
  print(f'interation number: {i}, with length of {len(df["news"][i])}')




interation number: 0, with length of 1336
interation number: 1, with length of 2123
interation number: 2, with length of 2159
interation number: 3, with length of 2674
interation number: 4, with length of 4827
interation number: 5, with length of 1103
interation number: 6, with length of 4079
interation number: 7, with length of 693
interation number: 8, with length of 3536
interation number: 9, with length of 991
interation number: 10, with length of 2180
interation number: 11, with length of 6277
interation number: 12, with length of 4222
interation number: 13, with length of 3305
interation number: 14, with length of 2019
interation number: 15, with length of 1416
interation number: 16, with length of 1795
interation number: 17, with length of 1118
interation number: 18, with length of 4636
interation number: 19, with length of 1541
interation number: 20, with length of 4035
interation number: 21, with length of 3380
interation number: 22, with length of 5174
interation number: 23, 

In [ ]:
len(df['news'][48]) # la 48 contient plus de 13k mots, on prendra celle la.

13206

In [ ]:
#doc = df['news'][48] #the one used for this project
doc = df['news'].sample().iloc[0] # random one

In [ ]:
# Cette fonction prend un texte brut (comme une chaîne de caractères) et le
# formate pour qu'il soit découpé en lignes d'une largeur spécifiée.
# Par défaut, la largeur est de 70 caractères si aucune valeur de width n'est
# spécifiée. Le texte est reformatté en introduisant des sauts de ligne pour
# respecter cette limite.


doc2 = textwrap.fill(doc, replace_whitespace = False, fix_sentence_endings= True)

In [ ]:
print(doc2)

Los buenos resultados del piloto Sergio Checo Pérez  en la Fórmula 1
le están generando réditos fuera de las pistas y nuevos patrocinios.
El último anuncio en ese sentido lo acaba de hacer Tequila Patrón una
marca premium de licores que suscribió una alianza con el piloto
mexicano.Después de casi haberse quedado sin un puesto en la parrilla
en 2020 Pérez es el más reciente piloto en unirse al club de los US10
millones en la Fórmula 1. Aun cuando su nuevo contrato con Redbull
Racing lo pone a la par de otros pilotos estrella como Carlos Sainz
Ferrari y Valteri Bottas Alfa Romeo el mexicano está varios pasos por
delante en cuanto a mercadeo y ventas pues en este aspecto es uno de
los mejores de la competición.Jaime Jañez CEO de Blackshark Sports
Marketing  Advertising explicó que Checo Pérez es uno de los tres
pilotos de la Fórmula 1 que más merchandising vende a nivel mundial.
De este total más de 50 corresponde a México donde hay más de 30
millones de fans de F1.Tengo mucho respeto por

In [ ]:
lines = doc2.split('.')# or \n or ,
len(lines)

12

In [ ]:
type(lines) #list of sentences

list

In [ ]:
for i in lines:
  print(i)
  print("_________")

Los buenos resultados del piloto Sergio Checo Pérez  en la Fórmula 1
le están generando réditos fuera de las pistas y nuevos patrocinios
_________

El último anuncio en ese sentido lo acaba de hacer Tequila Patrón una
marca premium de licores que suscribió una alianza con el piloto
mexicano
_________
Después de casi haberse quedado sin un puesto en la parrilla
en 2020 Pérez es el más reciente piloto en unirse al club de los US10
millones en la Fórmula 1
_________
 Aun cuando su nuevo contrato con Redbull
Racing lo pone a la par de otros pilotos estrella como Carlos Sainz
Ferrari y Valteri Bottas Alfa Romeo el mexicano está varios pasos por
delante en cuanto a mercadeo y ventas pues en este aspecto es uno de
los mejores de la competición
_________
Jaime Jañez CEO de Blackshark Sports
Marketing  Advertising explicó que Checo Pérez es uno de los tres
pilotos de la Fórmula 1 que más merchandising vende a nivel mundial
_________

De este total más de 50 corresponde a México donde hay más de

In [ ]:
#Now let's vectorize

tokenize = TfidfVectorizer( #vectorizer is a better name than tokenize
    stop_words = stopwords.words('spanish'),
    norm = 'l1'
    )

In [ ]:

X = tokenize.fit_transform(lines)
X
X.shape # no ()
#95 lines (tokens), 720 different words

#X est une matrice sparse (éparse), où chaque ligne correspond à un document
# ou une phrase, et chaque colonne à un mot unique (ou un token unique).

(12, 159)

In [ ]:
rows, columns = X.shape

for i in range(rows):
  for j in range(columns):
    print(X[i,j], end=' ')
  print()
#Here we print the value of each word in each document,
#that's why it's a sparse matrix


0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.09368147394588759 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.05784348366741577 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.07107021957099509 0.09368147394588759 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.09368147394588759 0.0 0.0 0.0 0.0 0.0 0.0 0.09368147394588759 0.0 0.0 0.0 0.0 0.0 0.06379102152707239 0.0 0.0 0.09368147394588759 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.05784348366741577 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.09368147394588759 0.0 0.0 0.09368147394588759 0.0 0.09368147394588759 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 
0.0 0.0 0.0 0.0 0.08861526323349911 0.0 0.0 0.0 0.08861526323349911 0.0 0.07610381743267111 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0

In [ ]:
# Now let's score tfidf each row

def get_score(tfidf_row):
    x = tfidf_row[tfidf_row != 0]
    return x.mean()


def get_score(tfidf_row): #Gemini version after the division by 0 proc error
    x = tfidf_row[tfidf_row != 0]
    # Check if 'x' is empty before calculating the mean
    if x.size == 0:
        return 0  # Return 0 if 'x' is empty to avoid division by zero
    else:
        return x.mean()

In [ ]:
# Now let's use that on every row of lines
# First, instantiate a null series of the size of lines (95)
# in order to store the scores
scores = np.zeros(len(lines))
scores

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
scores = np.zeros(len(lines))
for i in range(len(lines)):
    score = get_score(X[i,:])#score the whole line of X
    scores[i] = score

In [ ]:
scores #95 values, each corresponding to the mean tfidf score of each row of lines

array([0.08333333, 0.07692308, 0.06666667, 0.03703704, 0.05882353,
       0.125     , 0.1       , 0.1       , 0.04347826, 0.03703704,
       0.03448276, 0.        ])

In [ ]:
sort_idx = np.argsort(-scores)# get the indices of the sorted (deacreasing) values of scores
sort_idx

array([ 5,  6,  7,  0,  1,  2,  4,  8,  3,  9, 10, 11])

In [ ]:
print('Summary:')
sentences = []
for i in range(0,7):
  sentences.append([sort_idx[i], scores[sort_idx[i]], lines[sort_idx[i]]])
  print(f"{scores[sort_idx[i]]} : {lines[sort_idx[i]]}")

Summary:
0.125 : 
De este total más de 50 corresponde a México donde hay más de 30
millones de fans de F1
0.09999999999999999 : Tengo mucho respeto por los grandes esfuerzos
que hace la familia de Tequila Patrón para lograr un tequila
simplemente perfecto
0.09999999999999999 :   Con mi Tequila Patrón favorito Silver celebro
esta emocionante unión y lo que está por venir dijo Pérez
0.0833333333333333 : Los buenos resultados del piloto Sergio Checo Pérez  en la Fórmula 1
le están generando réditos fuera de las pistas y nuevos patrocinios
0.07692307692307693 : 
El último anuncio en ese sentido lo acaba de hacer Tequila Patrón una
marca premium de licores que suscribió una alianza con el piloto
mexicano
0.06666666666666665 : Después de casi haberse quedado sin un puesto en la parrilla
en 2020 Pérez es el más reciente piloto en unirse al club de los US10
millones en la Fórmula 1
0.058823529411764705 : Jaime Jañez CEO de Blackshark Sports
Marketing  Advertising explicó que Checo Pérez es uno

In [ ]:
sentences

[[5,
  0.125,
  '\nDe este total más de 50 corresponde a México donde hay más de 30\nmillones de fans de F1'],
 [6,
  0.09999999999999999,
  'Tengo mucho respeto por los grandes esfuerzos\nque hace la familia de Tequila Patrón para lograr un tequila\nsimplemente perfecto'],
 [7,
  0.09999999999999999,
  '  Con mi Tequila Patrón favorito Silver celebro\nesta emocionante unión y lo que está por venir dijo Pérez'],
 [0,
  0.0833333333333333,
  'Los buenos resultados del piloto Sergio Checo Pérez  en la Fórmula 1\nle están generando réditos fuera de las pistas y nuevos patrocinios'],
 [1,
  0.07692307692307693,
  '\nEl último anuncio en ese sentido lo acaba de hacer Tequila Patrón una\nmarca premium de licores que suscribió una alianza con el piloto\nmexicano'],
 [2,
  0.06666666666666665,
  'Después de casi haberse quedado sin un puesto en la parrilla\nen 2020 Pérez es el más reciente piloto en unirse al club de los US10\nmillones en la Fórmula 1'],
 [4,
  0.058823529411764705,
  'Jaime J

In [ ]:
# This 'summary' looks a little bit messy. The idea now
# would be to take the very first indice of these tokens (the indice of lines of this sentence)
# and sort it with this new index (we used the first inedexes to get the most important tokens)
# now we have them, we sort them in the original way

sentences_sorted = sorted(sentences, key = lambda x: x[0])
sentences_sorted

[[0,
  0.0833333333333333,
  'Los buenos resultados del piloto Sergio Checo Pérez  en la Fórmula 1\nle están generando réditos fuera de las pistas y nuevos patrocinios'],
 [1,
  0.07692307692307693,
  '\nEl último anuncio en ese sentido lo acaba de hacer Tequila Patrón una\nmarca premium de licores que suscribió una alianza con el piloto\nmexicano'],
 [2,
  0.06666666666666665,
  'Después de casi haberse quedado sin un puesto en la parrilla\nen 2020 Pérez es el más reciente piloto en unirse al club de los US10\nmillones en la Fórmula 1'],
 [4,
  0.058823529411764705,
  'Jaime Jañez CEO de Blackshark Sports\nMarketing  Advertising explicó que Checo Pérez es uno de los tres\npilotos de la Fórmula 1 que más merchandising vende a nivel mundial'],
 [5,
  0.125,
  '\nDe este total más de 50 corresponde a México donde hay más de 30\nmillones de fans de F1'],
 [6,
  0.09999999999999999,
  'Tengo mucho respeto por los grandes esfuerzos\nque hace la familia de Tequila Patrón para lograr un tequi