In [96]:
import numpy as np
import matplotlib.pyplot as plt
import string
from sklearn.model_selection import train_test_split

In [97]:
archives = ["/content/drive/Othercomputers/Mon ordinateur portable/Data Science/Text_Claasification/Benedetti.txt",
"/content/drive/Othercomputers/Mon ordinateur portable/Data Science/Text_Claasification/Neruda.txt"]

In [98]:
# Empty list
texts = []
labels = []

In [99]:
# strip()Enlève les espaces et autres caractères de fin de ligne (comme \n,
# \r, etc.) des deux côtés de la chaîne de caractères, c'est-à-dire aussi
# bien au début qu'à la fin.
# rstrip() Enlève les espaces et les caractères de fin de ligne uniquement à
# la fin (à droite) de la chaîne.

for label, f in enumerate(archives):
  print(f"{f} corresponds to {label}")

  with open(f, "r", encoding ='utf-8') as archive:
    for line in archive:
      print(line)
      line = line.rstrip().lower() #drop /n and lower
      line = line.translate(str.maketrans('','', string.punctuation)) # drop punctuation
      texts.append(line)
      labels.append(label)





/content/drive/Othercomputers/Mon ordinateur portable/Data Science/Text_Claasification/Benedetti.txt corresponds to 0
Poemas varios

Mario Benedetti



La buena tiniebla

Una mujer desnuda y en lo oscuro

genera un resplandor que da confianza

de modo que si sobreviene

un apagón o un desconsuelo

es conveniente y hasta imprescindible

tener a mano una mujer desnuda

entonces las paredes se acuarelan

el cielo raso se convierte en cielo

las telarañas vibran en su ángulo

los almanaques dominguean

y los ojos felices y felinos

miran y no se cansan de mirar

una mujer desnuda y en lo oscuro

una mujer querida o a querer

exorcisa por una vez la muerte.



Preliminar del miedo

Por sobre las terrazas alunadas

donde se aman cautelosamente los gatos

y los brillos esquivan las chimeneas

creo que nadie sabe lo que yo sé esta noche

algo aprendido a pedacitos y a pulsaciones

y que integra mi pánico tradicional modesto

¿cómo desmenuzar plácidamente el miedo

comprender por fin que no es

In [100]:
texts

['poemas varios',
 'mario benedetti',
 '',
 'la buena tiniebla',
 'una mujer desnuda y en lo oscuro',
 'genera un resplandor que da confianza',
 'de modo que si sobreviene',
 'un apagón o un desconsuelo',
 'es conveniente y hasta imprescindible',
 'tener a mano una mujer desnuda',
 'entonces las paredes se acuarelan',
 'el cielo raso se convierte en cielo',
 'las telarañas vibran en su ángulo',
 'los almanaques dominguean',
 'y los ojos felices y felinos',
 'miran y no se cansan de mirar',
 'una mujer desnuda y en lo oscuro',
 'una mujer querida o a querer',
 'exorcisa por una vez la muerte',
 '',
 '\x0cpreliminar del miedo',
 'por sobre las terrazas alunadas',
 'donde se aman cautelosamente los gatos',
 'y los brillos esquivan las chimeneas',
 'creo que nadie sabe lo que yo sé esta noche',
 'algo aprendido a pedacitos y a pulsaciones',
 'y que integra mi pánico tradicional modesto',
 '¿cómo desmenuzar plácidamente el miedo',
 'comprender por fin que no es una excusa',
 'sino un escalo

In [101]:
print(labels)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [102]:
train_text, test_text, Y_train, Y_test = train_test_split(texts, labels, test_size = 0.1, random_state = 42)

In [103]:
len(train_text), len(Y_train)

(1890, 1890)

In [104]:
len(test_text), len(Y_test)

(210, 210)

In [105]:
"""
"<unk>" is a convention that we use in NLP to represent unknowns words.
In this case, we assign 0 to this special word
"""

indice = 1
indice_words = {'unk' : 0}

In [106]:
for text in train_text:
  print(text)
  tokens = text.split()
  for token in tokens:
    print(token)
    if token not in indice_words:
      indice_words[token] = indice
      indice += 1


Le flux de sortie a été tronqué et ne contient que les 5000 dernières lignes.
alegre
alegre
de
que
no
sea
cierto
náufrago
náufrago
y a lo exterior regresan las cosas en ti ocultas
y
a
lo
exterior
regresan
las
cosas
en
ti
ocultas
ahora no es no puede ser la muerte
ahora
no
es
no
puede
ser
la
muerte
la furia triste el grito la soledad del mar
la
furia
triste
el
grito
la
soledad
del
mar
sin mis inmadureces
sin
mis
inmadureces
diptongos como caracoles
diptongos
como
caracoles
estoy en mi ventana
estoy
en
mi
ventana
y las cosas más triviales
y
las
cosas
más
triviales
en ún arbol añoso
en
ún
arbol
añoso
de alegre angustia
de
alegre
angustia
te acerques y te mires
te
acerques
y
te
mires

tan llena de nostalgias
tan
llena
de
nostalgias
siempre encuentro una palabra
siempre
encuentro
una
palabra
que a veces no caben las remembranzas
que
a
veces
no
caben
las
remembranzas
y sucesivamente así
y
sucesivamente
así
y en cambio tiene nombre su destino
y
en
cambio
tiene
nombre
su
destino

llega el otoñ

In [107]:
indice_words

{'unk': 0,
 'quizá': 1,
 'fue': 2,
 'una': 3,
 'hecatombe': 4,
 'de': 5,
 'esperanzas': 6,
 'y': 7,
 'el': 8,
 'entusiasmo': 9,
 'pobre': 10,
 'la': 11,
 'condena': 12,
 'todavía': 13,
 'llena': 14,
 'las': 15,
 'vidas': 16,
 'del': 17,
 'fuego': 18,
 'rescató': 19,
 'un': 20,
 'relojito': 21,
 'que': 22,
 'atrasaba': 23,
 'paciencias': 24,
 'estiradas': 25,
 'poema': 26,
 '8': 27,
 'cuando': 28,
 'ames': 29,
 'después': 30,
 'ella': 31,
 'besó': 32,
 'sus': 33,
 'labios': 34,
 'se': 35,
 'encendía': 36,
 'pedazo': 37,
 'sol': 38,
 'entre': 39,
 'mis': 40,
 'manos': 41,
 'cualquier': 42,
 'verdor': 43,
 'nuevo': 44,
 'los': 45,
 'almanaques': 46,
 'dominguean': 47,
 'en': 48,
 'esa': 49,
 'sola': 50,
 'manera': 51,
 'estar': 52,
 'solo': 53,
 'negra': 54,
 'melena': 55,
 'estiras': 56,
 'brazos': 57,
 'qué': 58,
 'pena': 59,
 'he': 60,
 'adiestrado': 61,
 'aquel': 62,
 'árbol': 63,
 'quejan': 64,
 'como': 65,
 'enfermos': 66,
 'hojas': 67,
 'le': 68,
 'importa': 69,
 'a': 70,
 'gente':

In [108]:
len(indice_words)

2718

In [109]:
# convert in int
train_text_int = []
test_text_int = []

for text in train_text: # for each text
  tokens = text.split() # tokenize the whole sentence
  entire_line = [indice_words[token] for token in tokens] #for each words in this sentence, extract its indice from indice_words previously built
  train_text_int.append(entire_line)#append the list of numbers (indices) to finally get a list of numbers equivalent to the sentences (which are list of words)



In [110]:
train_text

['quizá fue una hecatombe de esperanzas',
 'y el entusiasmo pobre y la condena',
 'todavía',
 'y llena de las vidas del fuego',
 'rescató un relojito que atrasaba',
 'paciencias estiradas',
 '\x0cpoema 8',
 'cuando ames',
 'después ella besó sus labios',
 'se encendía un pedazo de sol entre mis manos',
 'que cualquier verdor nuevo',
 '',
 '',
 'los almanaques dominguean',
 'y en esa sola manera de estar solo',
 'de la negra melena cuando estiras los brazos',
 'qué pena  de las manos que he adiestrado',
 'de aquel árbol se quejan como enfermos las hojas',
 'que le importa a la gente',
 'es fácil de arreglar',
 'después de la plenitud viene la soledad',
 '\x0ccurriculum',
 'un torturador no se redime suicidándose pero algo es algo',
 'y un pavo real de espléndido abanico',
 'o cautelosas mujeres',
 'bueno llorá',
 'defender la alegría como una trinchera',
 'el pájaro que emigra',
 '\x0césta es mi casa',
 'cruza encima de mi corazón sin detenerte',
 'azul pero lejano',
 '\x0ctodavía',
 'i

In [111]:
train_text_int

[[1, 2, 3, 4, 5, 6],
 [7, 8, 9, 10, 7, 11, 12],
 [13],
 [7, 14, 5, 15, 16, 17, 18],
 [19, 20, 21, 22, 23],
 [24, 25],
 [26, 27],
 [28, 29],
 [30, 31, 32, 33, 34],
 [35, 36, 20, 37, 5, 38, 39, 40, 41],
 [22, 42, 43, 44],
 [],
 [],
 [45, 46, 47],
 [7, 48, 49, 50, 51, 5, 52, 53],
 [5, 11, 54, 55, 28, 56, 45, 57],
 [58, 59, 5, 15, 41, 22, 60, 61],
 [5, 62, 63, 35, 64, 65, 66, 15, 67],
 [22, 68, 69, 70, 11, 71],
 [72, 73, 5, 74],
 [30, 5, 11, 75, 76, 11, 77],
 [78],
 [20, 79, 80, 35, 81, 82, 83, 84, 72, 84],
 [7, 20, 85, 86, 5, 87, 88],
 [89, 90, 91],
 [92, 93],
 [94, 11, 95, 65, 3, 96],
 [8, 97, 22, 98],
 [99, 72, 100, 101],
 [102, 103, 5, 100, 104, 105, 106],
 [107, 83, 108],
 [13],
 [109, 7, 110],
 [111],
 [11, 112, 17, 113],
 [26, 114],
 [115, 116, 22, 117, 118, 100, 119],
 [120, 121, 20, 122, 123, 45, 124, 125],
 [5, 45, 126, 127, 7, 5, 15, 128],
 [129, 130, 131, 132, 22, 133, 123, 134, 135, 65, 136, 132, 22, 68, 137],
 [130, 138, 139, 140, 8, 141],
 [8, 142, 143, 17, 144, 145, 11, 146

In [112]:
#same process for test text, except that the dictionnary may not know every word from test_text. So we use "get"
for text in test_text:
  tokens = text.split()
  entire_line = [indice_words.get(token, 0) for token in tokens]# If token exists as a key in indice_words, get returns the associated integer value.
  test_text_int.append(entire_line)                             #If token is not in indice_words, get returns the default value 0 (or any other value you specify).


In [113]:
test_text_int

[[527, 22, 0, 70, 765, 15, 67, 590],
 [1277],
 [83, 1048, 290, 0],
 [],
 [0, 7, 0],
 [105, 571, 299, 300, 0, 3, 1052, 1768, 382, 154, 155],
 [1624, 0, 70, 470, 524, 72, 8, 0],
 [0, 0, 5, 0],
 [0, 0],
 [0, 5, 968, 386, 70, 206, 15, 0],
 [7, 3, 512, 1133],
 [0],
 [7, 1181, 0, 5, 1547, 35, 68, 418, 419, 65, 20, 420],
 [158, 132, 22, 80, 330, 117, 448, 244, 1315],
 [1608, 268, 0, 350, 756, 123, 15, 41, 0],
 [382, 0],
 [],
 [72, 20, 0, 5, 0],
 [134, 898, 22, 303, 1052, 7, 2421],
 [449, 415, 45, 1644, 123, 11, 898, 17, 1172],
 [8, 708, 22, 0, 351, 70, 351],
 [164, 245, 768, 5, 0],
 [65, 1702, 0, 0],
 [80, 0, 17, 359],
 [7, 639, 157, 0],
 [7, 0, 1705, 45, 0, 70, 132, 687],
 [882, 105, 0],
 [],
 [281, 365, 206, 290, 2287],
 [5, 1181, 1168, 418, 0],
 [45, 0, 5, 11, 0],
 [45, 573, 5, 0, 70, 695, 1305],
 [0],
 [0, 70, 0, 0],
 [1474, 20, 0, 0, 256, 0],
 [7, 365, 65, 0],
 [],
 [35, 2097, 48, 189],
 [120, 0],
 [7, 20, 1622, 1623],
 [0, 0, 0],
 [7, 854],
 [0, 116, 768],
 [100, 165, 100, 251, 7, 252],

In [114]:
V = len(indice_words)

# Let's built (remembering the theory of markov chains, transition matrix and probability of transistionning from a state to another)
#And remember that we have problems filling with 0 in probas so fill with one
#Benedetti's transition matrix and probas of states
A0 = np.ones((V,V)) #V² size matrix of 1
pi0 = np.ones(V) #vector of V diomensions

#Neruda's transition matrix and probas of states
A1 = np.ones((V,V)) #V² size matrix of 1
pi1 = np.ones(V) #vector of V diomensions

In [115]:
A0

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [116]:
 #ex of tokens extracted from a text_as_int
 #[367, 63, 28, 63, 323, 842, 13, 304],
 #[503, 503, 65, 0, 29, 71, 1200],

def compute_counts(text_as_int, A, pi):
  for tokens in text_as_int: # tokens represent the list of ints corresponding to a sentence
    last_indice = None #for first indice of the sequence (367 and 503 for the 3 ex)
    for indice in tokens: #367,63,28...
      #we are in first word of the sequence
      if last_indice is None:
        pi[indice] += 1 #proba of the word indice 367
      else:
        A[last_indice, indice]  += 1 # proba of transition 367->63
      last_indice = indice #next round 63->28


In [117]:
# [t for t, y in zip(train_text_int, Y_train) if y == 0] creates a list of text
# sequences (likely represented as lists of integers, where each integer
# corresponds to a word) from train_text_int where the corresponding label in
# Y_train is 0.
# zip(train_text_int, Y_train) pairs each text sequence in train_text_int with
# its corresponding label in Y_train
compute_counts([ t for t, y in zip(train_text_int,Y_train) if y==0 ], A0, pi0)
compute_counts([ t for t, y in zip(train_text_int,Y_train) if y==1 ], A1, pi1)

In [118]:
A1 #very few are != from 1

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [119]:
pi0

array([1., 4., 2., ..., 1., 2., 1.])

In [120]:
# Now we have numbers corresponding to the number of times the word appears
# (resp. the sequence of words appear) for pi (resp. Ai)
#We then have to normalize to get proper probabilities

A0 /= A0.sum(axis = 1, keepdims=True)
pi0 /= pi0.sum()

A1 /= A1.sum(axis = 1, keepdims=True)
pi1 /= pi1.sum()

In [121]:
A0

array([[0.00036792, 0.00036792, 0.00036792, ..., 0.00036792, 0.00036792,
        0.00036792],
       [0.00036738, 0.00036738, 0.00073475, ..., 0.00036738, 0.00036738,
        0.00036738],
       [0.00036738, 0.00036738, 0.00036738, ..., 0.00036738, 0.00036738,
        0.00036738],
       ...,
       [0.00036792, 0.00036792, 0.00036792, ..., 0.00036792, 0.00036792,
        0.00036792],
       [0.00036792, 0.00036792, 0.00036792, ..., 0.00036792, 0.00036792,
        0.00036792],
       [0.00036792, 0.00036792, 0.00036792, ..., 0.00036792, 0.00036792,
        0.00036792]])

In [122]:
pi1 #0.00031918 = lowest proba = proba of a word that appeared only once at the beginniong of a sequence (but not 0)

array([0.00031516, 0.00031516, 0.00031516, ..., 0.00031516, 0.00031516,
       0.00031516])

In [123]:
#now put log to have numbers not 0.0003156 something

logA0 = np.log(A0)
logpi0 =np.log(pi0)
logA1 = np.log(A1)
logpi1 =np.log(pi1)

In [124]:
logA0

array([[-7.90765159, -7.90765159, -7.90765159, ..., -7.90765159,
        -7.90765159, -7.90765159],
       [-7.90912218, -7.90912218, -7.215975  , ..., -7.90912218,
        -7.90912218, -7.90912218],
       [-7.90912218, -7.90912218, -7.90912218, ..., -7.90912218,
        -7.90912218, -7.90912218],
       ...,
       [-7.90765159, -7.90765159, -7.90765159, ..., -7.90765159,
        -7.90765159, -7.90765159],
       [-7.90765159, -7.90765159, -7.90765159, ..., -7.90765159,
        -7.90765159, -7.90765159],
       [-7.90765159, -7.90765159, -7.90765159, ..., -7.90765159,
        -7.90765159, -7.90765159]])

In [125]:
count0 = sum(y == 0 for y in Y_train) # count labels of 1 in Ytrain
count1 = sum(y == 1 for y in Y_train) # labels 0
total = len(Y_train) # count0 +1
p0 = count0 / total # proba a priori of label 0
p1 = count1 / total # same for 1
logp0 = np.log(p0) #log of proba label 0
logp1 = np.log(p1) # same for 1
p0, p1 #75% benedetti 25% neruda

(0.7476190476190476, 0.2523809523809524)

In [126]:
# classifier building
class Classifier:
  def __init__(self, logAs, logpis, logpriors):
    self.logAs = logAs
    self.logpis = logpis
    self.logpriors = logpriors
    self.K = len(logpriors) # number of labels (len([0,1]) = 2 in our case)


  def _compute_log_likelihood(self, input_, class_): #proba of a piece of text (input_) to come from a class (class_)
    logA = self.logAs[class_] #Matrix of transition of the class (class_)
    logpi = self.logpis[class_] # same idea for prob

    last_indice = None
    logprob = 0

    for indice in input_:
      if last_indice is None:
        # First token of the sequence
        logprob += logpi[indice]
      else:
        #compute proba of trnsition froml previous word to current one
        logprob += logA[last_indice, indice]

      # Actualize last_indice for next iteration
      last_indice = indice
    return logprob



  def predict(self, inputs):
    predictions = np.zeros(len(inputs))
    for i, input_ in enumerate(inputs):
      #compute the log proba posterior for each class (label)
      posteriors = [self._compute_log_likelihood(input_, c) + self.logpriors[c] for c in range(self.K)] # o ne preidction for each class and we take the higher
      pred = np.argmax(posteriors)
      predictions[i] = pred
    return predictions

In [127]:
# each arrangment has to be sorted
clf = Classifier(logAs=[logA0, logA1] ,logpis=[logpi0, logpi1] ,logpriors=[logp0, logp1] )

Ptrain = clf.predict(train_text_int)

In [128]:
print(f"Train accuracy: {np.mean(Ptrain == Y_train)}")


Train accuracy: 0.9798941798941799


In [129]:
#where it went wrong => very few cause we use train data
diff_indices = np.where(Ptrain != Y_train)[0]
print(diff_indices)

[  11   75  133  278  292  311  317  418  478  482  512  553  738  753
  833  936 1031 1067 1073 1074 1140 1141 1266 1328 1362 1512 1533 1609
 1635 1664 1681 1697 1705 1712 1739 1766 1824 1834]


In [130]:
#Now with test data
Ptest = clf.predict(test_text_int)
print(f"Train accuracy: {np.mean(Ptest == Y_test)}")

Train accuracy: 0.8285714285714286
